// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
        if (kIsWeb){
            throw UnsupportedError(
                'DefaultFirebaseOptions have not been configured for web - '
                'you can reconfigure this by running the FlutterFire CLI again.'
            );
        }
        switch (defaultTargetPlatform) {
            case TargetPlatform.android:
                return android;
            case TargetPlatform.iOS:
                return ios;
            case TargetPlatform.macOS:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for macos - '
                    'you can reconfigure this by running the FlutterFire CLI again.'
                );
            case TargetPlatform.windows:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for windows - '
                    'you can reconfigure this by running the FlutterFire CLI again.'
                );
            case TargetPlatform.linux:
                throw UnsupportedError(
                    'DefaultFirebaseOptions have not been configured for linux - '
                    'you can reconfigure this by running the FlutterFire CLI again.'
                );
            default:
            throw UnsupportedError(
                'DefaultFirebaseOptions are not supported for this platform.'
            );
        }
    }

    static const FirebaseOptions android = FirebaseOptions(
        apiKey: 'AIzaSyDISVhB-Q9hfe8QeRLqjcVuYGUGoT0N68E',
        appId: '1:557757745316:android:2256c40a8a6ccd65ac7e31',
        messagingSenderId: '557757745316',
        projectId: 'fruits-hub-d70b6',
        storageBucket: 'fruits-hub-d70b6.firebasestorage.app'
    );

    static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyDNmo33ISpbN2C7JLVYbIS-wzYDEyY0C0w',
        appId: '1:557757745316:ios:f27a8fd546d24655ac7e31',
        messagingSenderId: '557757745316',
        projectId: 'fruits-hub-d70b6',
        storageBucket: 'fruits-hub-d70b6.firebasestorage.app',
        iosBundleId: 'com.example.fruitHub'
    );
}
